/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    About: typeof import('./src/components/home/About.vue')['default']
    AdminDetail: typeof import('./src/components/admin/AdminDetail.vue')['default']
    AdminHeader: typeof import('./src/components/admin/AdminHeader.vue')['default']
    AdminRecords: typeof import('./src/components/admin/AdminRecords.vue')['default']
    AdminSidebar: typeof import('./src/components/admin/AdminSidebar.vue')['default']
    AdminStats: typeof import('./src/components/admin/AdminStats.vue')['default']
    AdminToolBar: typeof import('./src/components/admin/AdminToolBar.vue')['default']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElCheckbox: typeof import('element-plus/es')['ElCheckbox']
    ElForm: typeof import('element-plus/es')['ElForm']
    ElFormItem: typeof import('element-plus/es')['ElFormItem']
    ElInput: typeof import('element-plus/es')['ElInput']
    Footer: typeof import('./src/components/home/Footer.vue')['default']
    Header: typeof import('./src/components/home/Header.vue')['default']
    HeroFeatures: typeof import('./src/components/home/HeroFeatures.vue')['default']
    ImageUploader: typeof import('./src/components/repair/ImageUploader.vue')['default']
    Process: typeof import('./src/components/home/Process.vue')['default']
    RepairCaseDisplay: typeof import('./src/components/home/RepairCaseDisplay.vue')['default']
    RestorationHistory: typeof import('./src/components/repair/RestorationHistory.vue')['default']
    RestorationPreview: typeof import('./src/components/repair/RestorationPreview.vue')['default']
    RestorationSettings: typeof import('./src/components/repair/RestorationSettings.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Sidebar: typeof import('./src/components/repair/Sidebar.vue')['default']
  }
}
