/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    About: typeof import('./src/components/home/About.vue')['default']
    AdminDetail: typeof import('./src/components/admin/AdminDetail.vue')['default']
    AdminHeader: typeof import('./src/components/admin/AdminHeader.vue')['default']
    AdminRecords: typeof import('./src/components/admin/AdminRecords.vue')['default']
    AdminSidebar: typeof import('./src/components/admin/AdminSidebar.vue')['default']
    AdminStats: typeof import('./src/components/admin/AdminStats.vue')['default']
    AdminToolBar: typeof import('./src/components/admin/AdminToolBar.vue')['default']
    ElAside: typeof import('element-plus/es')['ElAside']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElCard: typeof import('element-plus/es')['ElCard']
    ElCheckbox: typeof import('element-plus/es')['ElCheckbox']
    ElColorPicker: typeof import('element-plus/es')['ElColorPicker']
    ElContainer: typeof import('element-plus/es')['ElContainer']
    ElDivider: typeof import('element-plus/es')['ElDivider']
    ElEmpty: typeof import('element-plus/es')['ElEmpty']
    ElForm: typeof import('element-plus/es')['ElForm']
    ElFormItem: typeof import('element-plus/es')['ElFormItem']
    ElHeader: typeof import('element-plus/es')['ElHeader']
    ElInput: typeof import('element-plus/es')['ElInput']
    ElList: typeof import('element-plus/es')['ElList']
    ElListItem: typeof import('element-plus/es')['ElListItem']
    ElMain: typeof import('element-plus/es')['ElMain']
    ElOption: typeof import('element-plus/es')['ElOption']
    ElSelect: typeof import('element-plus/es')['ElSelect']
    ElSlider: typeof import('element-plus/es')['ElSlider']
    ElTag: typeof import('element-plus/es')['ElTag']
    ElTooltip: typeof import('element-plus/es')['ElTooltip']
    Footer: typeof import('./src/components/home/Footer.vue')['default']
    Header: typeof import('./src/components/home/Header.vue')['default']
    HeroFeatures: typeof import('./src/components/home/HeroFeatures.vue')['default']
    ImageUploader: typeof import('./src/components/repair/ImageUploader.vue')['default']
    LazyImage: typeof import('./src/components/common/LazyImage.vue')['default']
    Process: typeof import('./src/components/home/Process.vue')['default']
    RepairCaseDisplay: typeof import('./src/components/home/RepairCaseDisplay.vue')['default']
    RestorationHistory: typeof import('./src/components/repair/RestorationHistory.vue')['default']
    RestorationPreview: typeof import('./src/components/repair/RestorationPreview.vue')['default']
    RestorationSettings: typeof import('./src/components/repair/RestorationSettings.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Sidebar: typeof import('./src/components/repair/Sidebar.vue')['default']
  }
}
